// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztxwrpvwfctusluoqsio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0eHdycHZ3ZmN0dXNsdW9xc2lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3NjI3MTksImV4cCI6MjA1MTMzODcxOX0.tAQtTpIvBOt9HIK-6Jxd2G5-2_Ws8ql2W0ctn2cIKFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);